services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    restart: unless-stopped
    command:
      - --path.rootfs=/host
    pid: host
    expose: [9100]
    networks: [background]
    volumes:
      - /:/host:ro,rslave

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports: [9090:9090]
    volumes:
      - prometheus-volume:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks: [background]
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - netdata
      - node_exporter

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana-storage:/var/lib/grafana
    ports: [3300:3000]
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_NAME: CTEC
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_AUTH_ANONYMOUS_HIDE_VERSION: true
      GF_USERS_DEFAULT_LANGUAGE: detect
      GF_LOG_FILTERS: rendering:debug
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
    networks: [background]
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - prometheus

  netdata:
    image: netdata/netdata
    pid: host
    network_mode: host
    restart: unless-stopped
    expose: [19999]
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:

  prometheus-volume:
  grafana-storage:

networks:
  background:
