{
 "title": "CTEC",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Minecraft Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "minecraft_tick{type=\"tps\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A/$B*100", "type": "math" }
   ]
  },
  {
   "title": "MSPT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "minecraft_tick{type=\"mspt\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Base Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node_exporter\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(node_network_transmit_bytes_total[$__interval])*8) by (instance)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(node_network_receive_bytes_total[$__interval])*8) by (instance)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Used% Basic",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode='system'}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(node_disk_read_bytes_total[$__interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds)by(instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(node_disk_written_bytes_total[$__interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes - 0", "legendFormat": "__auto" }
   ]
  }
 ]
}